### ISSUE TITLE
求指教时间功能如何实现

### ISSUE THREAD

**Issue by yanyaoli** [Ho1L0w-By/Cuit-DoItYourSelf#1]
[CUIT课程中心助手](https://github.com/ooyq/cuit-helper/)
求指教时间功能如何实现

**Comment by Ho1L0w-By** [comment]
平台上，他为了存储视频的播放进度，会每隔一段时间发一个包，那个包里面有以毫秒计算的播放时间间隔。我现在的想法是获取视频的总时长，然后直接发个时间间隔的包到后台，再发完成的包就可以了

**Comment by Ho1L0w-By** [comment]
> [CUIT课程中心助手](https://github.com/ooyq/cuit-helper/) 求指教时间功能如何实现

平台上，他为了存储视频的播放进度，会每隔一段时间发一个包，那个包里面有以毫秒计算的播放时间间隔。我现在的想法是获取视频的总时长，然后直接发个时间间隔的包到后台，再发完成的包就可以了。之前实验的时候玩了一下，结果我现在视频阅读时间已经长的离谱了。

**Comment by yanyaoli** [comment]
好的，非常感谢，等你更新

**Comment by yanyaoli** [comment]
我能找到请求网址进行刷新时长（自带id），但是如果想要自动化的话，获取videoId和时长id貌似有点困难，有获取的方法吗？ @Ho1L0w-By
